# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 95d07cac19650a3723fd6f0d8e704d6b6e12497f1cbf86a09fd784a7b3c1209e0c27fc76903e6f1d51fb0674af4ab39fc7b96ba52ebbd72c1d6535fa5509038c

test:
  secret_key_base: 847429d0b759baa8c5ac965b364de0f3b05473663e6f96fb6360b7187596bf789edc7f1513c4bc1adb7911a32a3c7ef04f596026a003805b30bf2ca7cce55490

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
